import { Classified } from "@/lib/types";

export const MOCK_CLASSIFIEDS: Classified[] = [
  // Vehicles
  {
    id: "cl-001",
    seller_id: "member-007",
    seller_name: "Thomas Anderson",
    title: "1981 DMC-12 — Stainless, 5-speed, 62k miles — Excellent driver",
    description: "Selling my 1981 after 12 years of ownership. It's been an excellent car but I've upgraded to an EV build. PRV V6 rebuilt at 55k, timing chain done 7k miles ago, door struts replaced 2 years ago. A/C works, all gauges functional. Some minor stainless scratches but panels in great shape. Full service history in a binder. Based in Manhattan — can ship nationwide.",
    price: 38500,
    price_negotiable: true,
    category: "Vehicles",
    condition: "Good",
    location: "New York, NY",
    images: ["steel-gradient-1", "steel-gradient-2", "steel-gradient-3"],
    listed_date: "2026-03-15T10:00:00Z",
    is_sold: false,
    contact_email: "thomas.anderson@example.com",
  },
  {
    id: "cl-002",
    seller_id: "member-016",
    seller_name: "Rebecca Harris",
    title: "1982 DMC-12 Gold — Extremely rare, one of ~3 known factory gold examples",
    description: "This is one of approximately 3 known factory gold-plated DeLoreans in existence. The gold plating is 24 karat and covers the full exterior. Interior is custom tan leather. Engine is stock PRV V6. Only 9,800 miles from new — used for shows only. Has been featured in multiple major automotive publications. Serious inquiries with proof of funds only. Price is firm.",
    price: 185000,
    price_negotiable: false,
    category: "Vehicles",
    condition: "Concours",
    location: "Austin, TX",
    images: ["gold-gradient-1", "gold-gradient-2"],
    listed_date: "2026-02-01T10:00:00Z",
    is_sold: false,
    contact_email: "rebecca.harris@example.com",
  },
  {
    id: "cl-003",
    seller_id: "member-040",
    seller_name: "Andrew White",
    title: "1983 DMC-12 EV conversion — Tesla Model S motor, 250-mile range",
    description: "Completed EV conversion using Tesla Model S rear motor. 75kWh battery pack with 250-mile range. CCS2 and J1772 charging (Level 1, 2, and DC fast charge). Custom center console houses EV BMS display. Original PRV V6 and related components included with sale. Car drives beautifully — quiet, smooth, and instant torque. Based in Nashville, TN.",
    price: 72000,
    price_negotiable: true,
    category: "Vehicles",
    condition: "Excellent",
    location: "Nashville, TN",
    images: ["ev-gradient-1", "ev-gradient-2", "ev-gradient-3"],
    listed_date: "2026-03-10T10:00:00Z",
    is_sold: false,
    contact_email: "andrew.white@example.com",
  },
  {
    id: "cl-004",
    seller_id: "member-013",
    seller_name: "Daniel Lee",
    title: "1982 DMC-12 — Project car, solid body, needs engine work",
    description: "Offering my project 1982 for sale — I've run out of garage space with my other build. Body is solid, fiberglass underbody is straight with no cracks. PRV V6 has a knock at startup that goes away — likely a collapsed lifter. All four gull-wing seals need replacement. Interior complete but rough. Would benefit from a motivated hobbyist who has the time I don't. Priced to move.",
    price: 16500,
    price_negotiable: true,
    category: "Vehicles",
    condition: "Fair",
    location: "Seattle, WA",
    images: ["project-gradient-1"],
    listed_date: "2026-03-20T10:00:00Z",
    is_sold: false,
    contact_email: "daniel.lee@example.com",
  },
  {
    id: "cl-005",
    seller_id: "member-067",
    seller_name: "Lars Andersen",
    title: "1981 DMC-12 — UK import, right-hand drive conversion, LHD available",
    description: "Unusual opportunity: proper RHD-converted 1981 DeLorean. Conversion done in 1985 by a specialist in the UK and has been registered and road legal in the UK since. All steering and pedal box work done professionally. Passes annual MOT with no advisories. Located in Copenhagen but can arrange UK delivery.",
    price: 54000,
    price_negotiable: true,
    category: "Vehicles",
    condition: "Good",
    location: "Copenhagen, Denmark",
    images: ["uk-gradient-1", "uk-gradient-2"],
    listed_date: "2026-01-15T10:00:00Z",
    is_sold: true, // Already sold
    contact_email: "lars.andersen@example.com",
  },
  // Parts
  {
    id: "cl-006",
    seller_id: "member-010",
    seller_name: "Amanda Wilson",
    title: "NOS door struts — pair, still in original DMC packaging",
    description: "Found a pair of genuine NOS (new old stock) door struts in their original DMC cardboard packaging from the Dunmurry factory. Never installed. These are the real deal — not reproductions. Part number: 105698. Very rare find. Perfect for a concours restoration.",
    price: 850,
    price_negotiable: false,
    category: "Parts",
    condition: "New",
    location: "Detroit, MI",
    images: ["parts-gradient-1"],
    listed_date: "2026-03-01T10:00:00Z",
    is_sold: false,
    contact_email: "amanda.wilson@example.com",
    part_number: "105698",
  },
  {
    id: "cl-007",
    seller_id: "member-025",
    seller_name: "Derek Wright",
    title: "PRV V6 timing chain kit — complete set, unused",
    description: "Bought this kit when I was planning to do my own timing chain job — ended up selling the car before I got to it. Complete kit includes: chain, sprockets, tensioner, guides, and gaskets. From a reputable vendor. Still in the original boxes. Will ship USPS Priority.",
    price: 280,
    price_negotiable: false,
    category: "Parts",
    condition: "New",
    location: "Kansas City, MO",
    images: ["parts-gradient-2"],
    listed_date: "2026-02-28T10:00:00Z",
    is_sold: false,
    contact_email: "derek.wright@example.com",
    part_number: "PRV-TIMING-KIT-V2",
  },
  {
    id: "cl-008",
    seller_id: "member-031",
    seller_name: "Jason Carter",
    title: "Complete door seal set — weatherstripping all four openings",
    description: "Complete weatherstripping set: both door openings plus both windshield surround seals. These are the exact-fit reproduction seals from DMCH. Unused — bought for my restoration then decided to go NOS. Will significantly reduce wind noise and water ingress. Will ship flat in a large box.",
    price: 185,
    price_negotiable: true,
    category: "Parts",
    condition: "New",
    location: "Tampa, FL",
    images: ["parts-gradient-3"],
    listed_date: "2026-03-08T10:00:00Z",
    is_sold: false,
    contact_email: "jason.carter@example.com",
    part_number: "SEAL-SET-COMPLETE",
  },
  {
    id: "cl-009",
    seller_id: "member-009",
    seller_name: "Christopher Davis",
    title: "Set of 6 Bosch fuel injectors — cleaned and flow tested",
    description: "Set of 6 Bosch injectors removed from my 1982 during an engine refresh. Sent to RC Engineering for ultrasonic cleaning and flow testing. All 6 within 2% of each other. Matched set with flow reports included. These are the correct units for all 81-83 DMC-12s. Ready to bolt in.",
    price: 320,
    price_negotiable: false,
    category: "Parts",
    condition: "Like New",
    location: "Chicago, IL",
    images: ["parts-gradient-4"],
    listed_date: "2026-03-22T10:00:00Z",
    is_sold: false,
    contact_email: "christopher.davis@example.com",
    part_number: "BOSCH-0-280-150-206",
  },
  {
    id: "cl-010",
    seller_id: "member-070",
    seller_name: "Graham Spencer",
    title: "PRV V6 complete engine — rebuilt to factory spec, zero miles",
    description: "Frame-off restoration surplus — I ended up using my original engine after all. This is a freshly rebuilt PRV V6 from a specialist rebuilder. Zero miles on the rebuild. Bored .020 over, new pistons, rings, bearings, timing chain, water pump, and all gaskets. Ready to drop in. I'll include the full rebuild invoice showing all work done.",
    price: 4200,
    price_negotiable: true,
    category: "Parts",
    condition: "Like New",
    location: "Detroit, MI",
    images: ["engine-gradient-1", "engine-gradient-2"],
    listed_date: "2026-03-12T10:00:00Z",
    is_sold: false,
    contact_email: "graham.spencer@example.com",
    part_number: "PRV-V6-2850",
  },
  {
    id: "cl-011",
    seller_id: "member-015",
    seller_name: "Stephanie Walker",
    title: "Original 1982 dealer window sticker and build sheet",
    description: "Not a car part, but rare paper history: the original window Monroney sticker and dealer build sheet from a 1982 DMC-12 (VIN SCEDT26TC3B010452). The car itself was sold years ago but I kept the paperwork. Perfect addition to a provenance file for this specific VIN or for display.",
    price: 450,
    price_negotiable: true,
    category: "Parts",
    condition: "Good",
    location: "Charlotte, NC",
    images: ["paper-gradient-1"],
    listed_date: "2026-03-03T10:00:00Z",
    is_sold: false,
    contact_email: "stephanie.walker@example.com",
  },
  {
    id: "cl-012",
    seller_id: "member-022",
    seller_name: "Amber Hall",
    title: "Rear suspension uprights — complete set, freshly powdercoated",
    description: "Complete rear suspension upright set with fresh black powdercoating. Includes uprights, control arm bushings (new), and ball joints. Removed from my 1981 during coilover install. In excellent structural condition — just cleaned up and coated. Will fit all 81-83 DMC-12s.",
    price: 375,
    price_negotiable: true,
    category: "Parts",
    condition: "Good",
    location: "Cincinnati, OH",
    images: ["parts-gradient-5"],
    listed_date: "2026-03-19T10:00:00Z",
    is_sold: false,
    contact_email: "amber.hall@example.com",
  },
  // Accessories
  {
    id: "cl-013",
    seller_id: "member-001",
    seller_name: "James Schay",
    title: "Flux Capacitor replica — fully illuminated, 1:1 scale, prop-quality",
    description: "This is the one — professionally built flux capacitor prop replica by a Hollywood prop house. 1:1 scale, mounts to the firewall exactly as in the movie. Full LED illumination, random flicker pattern, and the iconic Y-shaped casing. Powered by 12V from the car's electrical system. Comes with mounting hardware and wiring harness. Yes, it goes 1.21 gigawatts.",
    price: 650,
    price_negotiable: false,
    category: "Accessories",
    condition: "Like New",
    location: "Portland, OR",
    images: ["flux-gradient-1"],
    listed_date: "2026-03-25T10:00:00Z",
    is_sold: false,
    contact_email: "james.schay@example.com",
  },
  {
    id: "cl-014",
    seller_id: "member-036",
    seller_name: "Olivia Phillips",
    title: "DOA 40th Anniversary leather jacket — size Large, worn once",
    description: "Bought this at the 2023 DeLorean Expo — the limited edition 40th anniversary leather jacket. It's beautiful but honestly just not my style. Black leather, silver DMC wings embroidered on back, 40th anniversary patch on chest. Worn at one car show. Would fit a medium or large build.",
    price: 180,
    price_negotiable: true,
    category: "Accessories",
    condition: "Like New",
    location: "Salt Lake City, UT",
    images: ["jacket-gradient-1"],
    listed_date: "2026-03-14T10:00:00Z",
    is_sold: false,
    contact_email: "olivia.phillips@example.com",
  },
  {
    id: "cl-015",
    seller_id: "member-044",
    seller_name: "Brittany Cole",
    title: "Scale model collection — 12 die-cast DeLorean DMC-12 models",
    description: "Selling my collection of 12 die-cast DeLorean models accumulated over 15 years. Includes: Sunstar 1:18 scale (2 units), Hot Wheels premium versions (5 units), and various 1:24 and 1:43 scale. Some are the rare gold and black variants. Full collection photos available. Priced as a lot — not splitting.",
    price: 290,
    price_negotiable: true,
    category: "Accessories",
    condition: "Good",
    location: "Baltimore, MD",
    images: ["models-gradient-1"],
    listed_date: "2026-02-20T10:00:00Z",
    is_sold: false,
    contact_email: "brittany.cole@example.com",
  },
  {
    id: "cl-016",
    seller_id: "member-027",
    seller_name: "Grace Adams",
    title: "DeLorean leather steering wheel cover — Momo style, custom stitched",
    description: "High-quality leather steering wheel cover specifically patterned for the DeLorean's unique steering wheel shape. Hand-stitched in black leather with red stitching. Already been laced on once and removed — a bit tricky to install but makes the wheel look and feel fantastic. Would fit any 81-83 DMC-12.",
    price: 95,
    price_negotiable: false,
    category: "Accessories",
    condition: "Like New",
    location: "Louisville, KY",
    images: ["wheel-gradient-1"],
    listed_date: "2026-03-07T10:00:00Z",
    is_sold: false,
    contact_email: "grace.adams@example.com",
  },
  {
    id: "cl-017",
    seller_id: "member-055",
    seller_name: "Pieter van den Berg",
    title: "Framed DeLorean factory photography — set of 8, original prints",
    description: "Selling a set of 8 original factory photographs from the Dunmurry facility, circa 1981. These were acquired from a former DMC employee and show the production line, final assembly, and QC inspection. Beautifully framed in brushed steel frames (appropriate!). Great for a garage or man cave display. Shipping from Amsterdam — will ship with full insurance.",
    price: 1200,
    price_negotiable: true,
    category: "Accessories",
    condition: "Good",
    location: "Amsterdam, Netherlands",
    images: ["photos-gradient-1"],
    listed_date: "2026-03-01T10:00:00Z",
    is_sold: false,
    contact_email: "pieter.vandenberg@example.com",
  },
  // Services
  {
    id: "cl-018",
    seller_id: "member-009",
    seller_name: "Christopher Davis",
    title: "Mobile pre-purchase inspection — Midwest region, $250 flat fee",
    description: "Offering mobile PPI service for prospective DeLorean buyers in the Midwest (IL, IN, OH, MI, WI, MN, IA, MO within 150 miles of Chicago). I'm a master technician with 20 years of DeLorean experience and have inspected over 80 cars. Service includes: 2-hour visual and mechanical inspection, road test, written report with photos, phone call to discuss findings. $250 flat fee. Book 2 weeks in advance.",
    price: 250,
    price_negotiable: false,
    category: "Services",
    condition: "New",
    location: "Chicago, IL",
    images: ["service-gradient-1"],
    listed_date: "2026-01-01T10:00:00Z",
    is_sold: false,
    contact_email: "christopher.davis@example.com",
  },
  {
    id: "cl-019",
    seller_id: "member-010",
    seller_name: "Amanda Wilson",
    title: "Stainless steel detailing service — DeLorean specialist, Detroit area",
    description: "Professional stainless steel restoration and detailing specifically for DeLorean DMC-12s. Service includes: thorough cleaning, rust/stain treatment, directional polishing to factory spec, protective wax coating. Cars come out looking spectacular. $400 for full exterior polish. Mobile service available within 50 miles of Detroit.",
    price: 400,
    price_negotiable: false,
    category: "Services",
    condition: "New",
    location: "Detroit, MI",
    images: ["detailing-gradient-1"],
    listed_date: "2026-02-01T10:00:00Z",
    is_sold: false,
    contact_email: "amanda.wilson@example.com",
  },
  {
    id: "cl-020",
    seller_id: "member-050",
    seller_name: "Zena Cross",
    title: "EV conversion consulting — planning and spec, $150/hr",
    description: "Offering consulting services for DOA members considering or planning an EV conversion. I've done two complete conversions and helped three others plan theirs. Services: battery sizing and selection, motor selection, charger spec, wiring harness planning, BMS programming, and vendor recommendations. I can save you thousands in mistakes. Available via Zoom or in-person in the San Jose, CA area.",
    price: 150,
    price_negotiable: false,
    category: "Services",
    condition: "New",
    location: "Fresno, CA",
    images: ["ev-service-gradient-1"],
    listed_date: "2026-02-15T10:00:00Z",
    is_sold: false,
    contact_email: "zena.cross@example.com",
  },
  // Wanted
  {
    id: "cl-021",
    seller_id: "member-014",
    seller_name: "Michelle Thompson",
    title: "WANTED: Original 1981-83 DeLorean radio / cassette unit",
    description: "Seeking an original Blaupunkt or Lear Siegler cassette unit as fitted to 1981-83 DMC-12s. Mine was replaced at some point with an aftermarket unit. I want to restore to factory spec. Looking for working or restorable condition. Will pay fairly for the right unit. Please contact with photos and price.",
    price: 0, // Wanted ad — no price set
    price_negotiable: true,
    category: "Wanted",
    condition: "Good",
    location: "Denver, CO",
    images: ["wanted-gradient-1"],
    listed_date: "2026-03-10T10:00:00Z",
    is_sold: false,
    contact_email: "michelle.thompson@example.com",
  },
  {
    id: "cl-022",
    seller_id: "member-032",
    seller_name: "Karen Mitchell",
    title: "WANTED: Original DeLorean service manuals — full factory set",
    description: "Looking for the complete factory service manual set for the DMC-12 — ideally all volumes in good condition. I know they've been reproduced but I'd prefer originals for my documentation collection. Also interested in any original dealer sales brochures or press kits. Richmond, VA but will pay shipping.",
    price: 0,
    price_negotiable: true,
    category: "Wanted",
    condition: "Good",
    location: "Richmond, VA",
    images: ["wanted-gradient-2"],
    listed_date: "2026-02-25T10:00:00Z",
    is_sold: false,
    contact_email: "karen.mitchell@example.com",
  },
  // A couple sold listings for realism
  {
    id: "cl-023",
    seller_id: "member-002",
    seller_name: "Robert Mitchell",
    title: "[SOLD] 1982 DMC-12 Black — fully restored, concours quality",
    description: "Full frame-off restoration completed 2024. All original paint stripped and refinished in period-correct black. Every mechanical system rebuilt. Won Best in Class at the 2024 Expo. SOLD — thanks for all the interest!",
    price: 85000,
    price_negotiable: false,
    category: "Vehicles",
    condition: "Concours",
    location: "Los Angeles, CA",
    images: ["black-gradient-1"],
    listed_date: "2025-11-01T10:00:00Z",
    is_sold: true,
    contact_email: "robert.mitchell@example.com",
  },
  {
    id: "cl-024",
    seller_id: "member-018",
    seller_name: "Ryan Robinson",
    title: "[SOLD] Original door strut set — off a 1983, driver quality",
    description: "Original struts off my 1983 after I upgraded to SunStar hydraulics. Both still work but are getting weak. Good for a parts car or someone doing a budget restoration. SOLD.",
    price: 120,
    price_negotiable: false,
    category: "Parts",
    condition: "Fair",
    location: "San Diego, CA",
    images: ["parts-gradient-6"],
    listed_date: "2026-01-10T10:00:00Z",
    is_sold: true,
    contact_email: "ryan.robinson@example.com",
  },
  {
    id: "cl-025",
    seller_id: "member-042",
    seller_name: "Earl Foster",
    title: "1983 DMC-12 — 5-speed, stainless, Wyoming barn find",
    description: "Just found this 1983 in a Cheyenne, WY barn while doing estate work. Complete car, engine turns over but hasn't run in 10+ years. Zero rust — Wyoming dry storage is a blessing. Fiberglass is perfect. Interior is rough. A perfect restoration candidate. Price reflects the work needed.",
    price: 22000,
    price_negotiable: true,
    category: "Vehicles",
    condition: "Fair",
    location: "Cheyenne, WY",
    images: ["barn-gradient-1"],
    listed_date: "2026-03-26T10:00:00Z",
    is_sold: false,
    contact_email: "earl.foster@example.com",
  },
];

export const getClassifiedsByCategory = (category: string) =>
  MOCK_CLASSIFIEDS.filter((c) => c.category === category && !c.is_sold);

export const getActiveClassifieds = () =>
  MOCK_CLASSIFIEDS.filter((c) => !c.is_sold);

export const getClassifiedById = (id: string) =>
  MOCK_CLASSIFIEDS.find((c) => c.id === id);
