import { Event } from "@/lib/types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "event-001",
    title: "DeLorean Expo 2026",
    description: "The world's largest DeLorean gathering returns to the DeLorean Motor Company facility in Humble, Texas. Three days of car shows, technical seminars, group drives, and camaraderie. The centerpiece event of the DOA calendar year. Featuring a special exhibit: '40 Years of DeLorean Owners Association'. Vendor village, charity auction, and the legendary evening banquet.",
    type: "Annual Expo",
    date: "2026-08-14",
    end_date: "2026-08-17",
    location: "DeLorean Motor Company, 24625 State Hwy 198",
    city: "Humble",
    state: "TX",
    country: "USA",
    lat: 29.9988,
    lng: -95.2581,
    organizer: "DeLorean Owners Association",
    rsvp_count: 287,
    max_attendees: 500,
    is_members_only: false,
    image_placeholder: "expo-gradient",
    is_past: false,
  },
  {
    id: "event-002",
    title: "Northeast Spring Meet — Newport, RI",
    description: "The Northeast chapter's annual spring gathering at Bellevue Avenue in Newport. Cars will be displayed against the backdrop of the Newport mansions for a photoshoot that has become legendary in DeLorean circles. Followed by a group lunch at the Black Pearl restaurant in Bowen's Wharf.",
    type: "Chapter Meet",
    date: "2026-04-26",
    end_date: "2026-04-26",
    location: "Bellevue Avenue",
    city: "Newport",
    state: "RI",
    country: "USA",
    lat: 41.4776,
    lng: -71.3120,
    organizer: "Northeast Chapter",
    chapter: "Northeast",
    rsvp_count: 34,
    max_attendees: 60,
    is_members_only: true,
    image_placeholder: "newport-gradient",
    is_past: false,
  },
  {
    id: "event-003",
    title: "UK Spring Meet — Blenheim Palace, Oxford",
    description: "The UK chapter's premier spring event at Blenheim Palace grounds. Up to 80 DeLoreans on the gravel forecourt with the Palace as backdrop. Group lunch at the Woodstock Arms and an optional walking tour of the Palace. This annual event has grown to be the largest DeLorean gathering in Europe.",
    type: "Chapter Meet",
    date: "2026-05-10",
    end_date: "2026-05-10",
    location: "Blenheim Palace",
    city: "Woodstock",
    state: "Oxford",
    country: "UK",
    lat: 51.8441,
    lng: -1.3619,
    organizer: "UK Chapter",
    chapter: "UK",
    rsvp_count: 52,
    max_attendees: 80,
    is_members_only: false,
    image_placeholder: "uk-gradient",
    is_past: false,
  },
  {
    id: "event-004",
    title: "EV Conversion Workshop — Online Webinar",
    description: "Join us for a 3-hour deep dive into electric vehicle conversions for the DMC-12. Hosted by Jennifer Williams (aerospace engineer and EV conversion specialist) and Zena Cross (two-time converter). Topics: motor selection, battery chemistry, BMS basics, wiring, and regulatory compliance. Q&A session included. Recording available to members.",
    type: "Webinar",
    date: "2026-04-12",
    end_date: "2026-04-12",
    location: "Online — Zoom",
    city: "Online",
    state: "",
    country: "Global",
    organizer: "DOA Technical Committee",
    rsvp_count: 143,
    is_members_only: true,
    image_placeholder: "webinar-gradient",
    is_past: false,
  },
  {
    id: "event-005",
    title: "Concours d'Elegance at Pebble Beach",
    description: "Multiple DOA members will be displaying their DeLoreans at the informal parking lot gathering outside the main Concours event. Not an official show class (yet), but our informal gathering has become a tradition. Come see the finest examples from the DOA collection alongside the world's greatest automobiles.",
    type: "Car Show",
    date: "2026-08-16",
    end_date: "2026-08-16",
    location: "Pebble Beach Golf Links",
    city: "Pebble Beach",
    state: "CA",
    country: "USA",
    lat: 36.5686,
    lng: -121.9538,
    organizer: "Pacific Chapter",
    chapter: "Pacific",
    rsvp_count: 12,
    max_attendees: 20,
    is_members_only: false,
    image_placeholder: "pebble-gradient",
    is_past: false,
  },
  {
    id: "event-006",
    title: "PRV V6 Technical Workshop — Chicago",
    description: "Hands-on technical workshop at Christopher Davis's shop in the Chicago suburbs. Half-day session covering: timing chain inspection and replacement, common oil leak sources, fuel system maintenance, and electrical diagnosis. Limited to 12 participants so each person gets quality hands-on time. Bring your own car or work on the shop demo car.",
    type: "Tech Workshop",
    date: "2026-05-23",
    end_date: "2026-05-23",
    location: "Davis Automotive Workshop",
    city: "Evanston",
    state: "IL",
    country: "USA",
    lat: 42.0451,
    lng: -87.6877,
    organizer: "Midwest Chapter",
    chapter: "Midwest",
    rsvp_count: 11,
    max_attendees: 12,
    is_members_only: true,
    image_placeholder: "workshop-gradient",
    is_past: false,
  },
  {
    id: "event-007",
    title: "Pacific Coast Highway Group Drive",
    description: "The annual PCH Drive — 250 miles of the most scenic road in America. Start: Santa Monica Pier, 9am. End: San Luis Obispo. Stops at Malibu, Santa Barbara, and Pismo Beach. Lunch at the Hitching Post Steakhouse in Buellton. This drive has become a Pacific chapter tradition and never disappoints.",
    type: "Chapter Meet",
    date: "2026-06-21",
    end_date: "2026-06-21",
    location: "Santa Monica Pier",
    city: "Santa Monica",
    state: "CA",
    country: "USA",
    lat: 34.0097,
    lng: -118.4991,
    organizer: "Pacific Chapter",
    chapter: "Pacific",
    rsvp_count: 18,
    max_attendees: 35,
    is_members_only: false,
    image_placeholder: "pch-gradient",
    is_past: false,
  },
  {
    id: "event-008",
    title: "Southeast Summer Cruise — Charleston, SC",
    description: "The Southeast chapter's summer event in beautiful Charleston, SC. Friday evening cocktail gathering at the historic Mills House Hotel, Saturday morning cruise through the historic district and along the Battery, Saturday afternoon cars on display at Waterfront Park. Overnight stay recommended.",
    type: "Chapter Meet",
    date: "2026-07-11",
    end_date: "2026-07-12",
    location: "Waterfront Park",
    city: "Charleston",
    state: "SC",
    country: "USA",
    lat: 32.7765,
    lng: -79.9311,
    organizer: "Southeast Chapter",
    chapter: "Southeast",
    rsvp_count: 26,
    max_attendees: 50,
    is_members_only: false,
    image_placeholder: "charleston-gradient",
    is_past: false,
  },
  {
    id: "event-009",
    title: "DeLorean History Deep Dive — Online Webinar",
    description: "A 2-hour presentation on the complete history of the DeLorean DMC-12 — from John DeLorean's departure from GM to the Dunmurry factory, the troubled production years, John DeLorean's legal troubles, and the resurrection of the brand. Featuring rare photographs and documents not previously published.",
    type: "Webinar",
    date: "2026-03-08",
    end_date: "2026-03-08",
    location: "Online — Zoom",
    city: "Online",
    state: "",
    country: "Global",
    organizer: "DOA Historical Committee",
    rsvp_count: 198,
    is_members_only: false,
    image_placeholder: "history-gradient",
    is_past: true, // Past event
  },
  {
    id: "event-010",
    title: "New Year's Day Shakedown Drive — Phoenix",
    description: "Welcome 2026 by taking your DeLorean out on January 1st! The Southwest chapter's annual New Year's Drive through the Sonoran Desert. Start: Desert Botanical Garden parking lot, 10am. 80-mile route through Cave Creek, Carefree, and back through Scottsdale. Light brunch after at a local favorite.",
    type: "Chapter Meet",
    date: "2026-01-01",
    end_date: "2026-01-01",
    location: "Desert Botanical Garden",
    city: "Phoenix",
    state: "AZ",
    country: "USA",
    lat: 33.4609,
    lng: -111.9446,
    organizer: "Southwest Chapter",
    chapter: "Southwest",
    rsvp_count: 19,
    max_attendees: 40,
    is_members_only: false,
    image_placeholder: "phoenix-gradient",
    is_past: true,
  },
  {
    id: "event-011",
    title: "Midwest Winter Social — Chicago",
    description: "The annual indoor winter gathering for Midwest chapter members. Cars stay warm in the garage — this one is about people, good food, and good conversation. Held at the Lincoln Square Taproom, private room. Chicago-style deep dish, craft beers, and the annual awards ceremony (Best Restoration, Most Miles Driven, Most Interesting Modification).",
    type: "Chapter Meet",
    date: "2026-02-07",
    end_date: "2026-02-07",
    location: "Lincoln Square Taproom",
    city: "Chicago",
    state: "IL",
    country: "USA",
    lat: 41.9668,
    lng: -87.6875,
    organizer: "Midwest Chapter",
    chapter: "Midwest",
    rsvp_count: 31,
    max_attendees: 50,
    is_members_only: true,
    image_placeholder: "chicago-gradient",
    is_past: true,
  },
  {
    id: "event-012",
    title: "Annual Member Meeting — Online",
    description: "The annual DOA membership meeting. Agenda: treasurer's report, chapter reports, election of board members, magazine update, 2027 event calendar preview, and member Q&A. All members are encouraged to attend. Voting on two proposed bylaw amendments. Recording available post-meeting.",
    type: "Other",
    date: "2026-09-20",
    end_date: "2026-09-20",
    location: "Online — Zoom",
    city: "Online",
    state: "",
    country: "Global",
    organizer: "DeLorean Owners Association",
    rsvp_count: 74,
    is_members_only: true,
    image_placeholder: "meeting-gradient",
    is_past: false,
  },
];

export const getUpcomingEvents = () =>
  MOCK_EVENTS.filter((e) => !e.is_past).sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );

export const getPastEvents = () =>
  MOCK_EVENTS.filter((e) => e.is_past).sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );

export const getEventById = (id: string) => MOCK_EVENTS.find((e) => e.id === id);
