import { ForumCategory, ForumThread, ForumReply } from "@/lib/types";

export const FORUM_CATEGORIES: ForumCategory[] = [
  {
    id: "cat-001",
    name: "General Discussion",
    description: "Talk about anything DeLorean — ownership, shows, life with a gull-wing.",
    icon: "MessageSquare",
    thread_count: 142,
    post_count: 1847,
    last_post_date: "2026-03-26T14:22:00Z",
  },
  {
    id: "cat-002",
    name: "Tech Talk",
    description: "Technical questions, DIY guides, mechanical and electrical issues.",
    icon: "Wrench",
    thread_count: 318,
    post_count: 4293,
    last_post_date: "2026-03-27T08:15:00Z",
  },
  {
    id: "cat-003",
    name: "Buying & Selling Tips",
    description: "Advice on buying your first DMC-12, what to look for, fair pricing.",
    icon: "DollarSign",
    thread_count: 87,
    post_count: 934,
    last_post_date: "2026-03-25T19:44:00Z",
  },
  {
    id: "cat-004",
    name: "Events & Meets",
    description: "Discuss upcoming shows, expos, chapter meets, and road trips.",
    icon: "Calendar",
    thread_count: 64,
    post_count: 712,
    last_post_date: "2026-03-26T21:08:00Z",
  },
  {
    id: "cat-005",
    name: "EV Conversions",
    description: "Electric powertrain conversions — planning, builds, maintenance.",
    icon: "Zap",
    thread_count: 53,
    post_count: 891,
    last_post_date: "2026-03-27T06:30:00Z",
  },
  {
    id: "cat-006",
    name: "Restoration",
    description: "Full restorations, partial refreshes, parts sourcing, and body work.",
    icon: "PaintBucket",
    thread_count: 96,
    post_count: 1234,
    last_post_date: "2026-03-24T16:55:00Z",
  },
  {
    id: "cat-007",
    name: "Regional",
    description: "Chapter-specific discussions — Northeast, Southeast, Pacific, UK, etc.",
    icon: "MapPin",
    thread_count: 41,
    post_count: 387,
    last_post_date: "2026-03-26T10:17:00Z",
  },
  {
    id: "cat-008",
    name: "Off-Topic",
    description: "Sports cars, movies, Back to the Future, and anything off-topic.",
    icon: "Coffee",
    thread_count: 29,
    post_count: 418,
    last_post_date: "2026-03-25T22:33:00Z",
  },
];

export const FORUM_THREADS: ForumThread[] = [
  // General Discussion
  {
    id: "thread-001",
    category_id: "cat-001",
    title: "Just picked up my first DMC-12 — 1982, 38k miles, needs some love!",
    body: "After 15 years of dreaming, I finally did it. Just trailered home a 1982 DMC-12 with 38,000 miles from an estate sale in Indiana. The previous owner had it since 1989. Engine runs but needs timing work. Doors open and close beautifully. Interior is surprisingly solid — original carpet shows wear but the leather is supple. I'm thrilled and terrified in equal measure. What should I tackle first?",
    author_id: "member-008",
    author_name: "Patricia Brown",
    created_at: "2026-03-20T15:30:00Z",
    updated_at: "2026-03-26T14:22:00Z",
    reply_count: 23,
    view_count: 847,
    is_pinned: false,
    is_locked: false,
    tags: ["new owner", "1982", "first car", "advice needed"],
  },
  {
    id: "thread-002",
    category_id: "cat-001",
    title: "DOA Member Survey 2026 Results — What We Learned",
    body: "Hi everyone — we just completed our annual membership survey and wanted to share the results. We had 312 responses this year (a record!). Key findings: 67% own a manual transmission car, 18% have completed or are planning an EV conversion, the average member has owned their DeLorean for 8.3 years, and 94% say the DOA community is the #1 resource for DeLorean ownership. Full report attached in the Magazine section.",
    author_id: "member-001",
    author_name: "James Schay",
    created_at: "2026-03-15T10:00:00Z",
    updated_at: "2026-03-22T09:15:00Z",
    reply_count: 41,
    view_count: 1923,
    is_pinned: true,
    is_locked: false,
    tags: ["survey", "community", "statistics"],
  },
  {
    id: "thread-003",
    category_id: "cat-001",
    title: "Ladies of Stainless — New Women's Chapter Initiative",
    body: "Excited to announce the launch of our 'Ladies of Stainless' initiative — a dedicated space within DOA for women DeLorean owners and enthusiasts. We currently have 47 women members and our community is growing. We'll have a dedicated forum section, a group drive at this year's Expo, and a feature in the upcoming magazine issue. All are welcome to support this initiative!",
    author_id: "member-011",
    author_name: "Kevin Martinez",
    created_at: "2026-02-28T12:00:00Z",
    updated_at: "2026-03-10T16:40:00Z",
    reply_count: 56,
    view_count: 2341,
    is_pinned: true,
    is_locked: false,
    tags: ["women", "community", "initiative", "diversity"],
  },
  // Tech Talk
  {
    id: "thread-004",
    category_id: "cat-002",
    title: "PRV V6 timing chain replacement — complete guide with photos",
    body: "After doing this job twice (once on my own car, once helping a chapter member), I figured I'd write the definitive guide. The PRV V6 timing chain is famously temperamental but completely manageable if you're methodical. Total job time: about 14 hours if you're not rushing. You'll need: Timing chain kit (multiple vendors, I recommend DMC Texas), timing light, degree wheel, specialty tool for the cam sprocket... [continues with full instructions]",
    author_id: "member-009",
    author_name: "Christopher Davis",
    created_at: "2026-01-15T09:00:00Z",
    updated_at: "2026-03-27T08:15:00Z",
    reply_count: 87,
    view_count: 4892,
    is_pinned: true,
    is_locked: false,
    tags: ["PRV V6", "timing chain", "DIY", "guide"],
  },
  {
    id: "thread-005",
    category_id: "cat-002",
    title: "Best source for door strut replacements in 2026?",
    body: "My struts are giving up the ghost — the doors still open but they don't hold position at the full-up stop anymore. I know there are a few vendors: DMC Texas, DMCH, and some aftermarket options. Who's been happy with what recently? I don't want to buy cheap Chinese knockoffs and I'm willing to pay for quality. Also open to suggestions on the hydraulic conversion — worth it?",
    author_id: "member-013",
    author_name: "Daniel Lee",
    created_at: "2026-03-10T14:22:00Z",
    updated_at: "2026-03-25T11:33:00Z",
    reply_count: 31,
    view_count: 1203,
    is_pinned: false,
    is_locked: false,
    tags: ["door struts", "parts", "vendors", "maintenance"],
  },
  {
    id: "thread-006",
    category_id: "cat-002",
    title: "Fuel injector cleaning vs replacement — when do you cross the line?",
    body: "My car is running slightly rough at idle and I suspect the injectors. They've never been cleaned in 40 years (I recently bought the car). At what point do you just replace them versus sending them out for ultrasonic cleaning? The factory Bosch injectors are still available NOS from DMC Texas but they're pricey. New Bosch equivalent units are much cheaper. Thoughts from those who've been down this road?",
    author_id: "member-030",
    author_name: "Iris Nelson",
    created_at: "2026-03-05T18:45:00Z",
    updated_at: "2026-03-21T20:10:00Z",
    reply_count: 19,
    view_count: 743,
    is_pinned: false,
    is_locked: false,
    tags: ["fuel injectors", "tuning", "maintenance", "Bosch"],
  },
  {
    id: "thread-007",
    category_id: "cat-002",
    title: "Stainless steel cleaning and polishing — the definitive thread",
    body: "Every few months someone asks about polishing the stainless, so let me compile everything in one place. The DeLorean's body is made of austenitic 304 stainless steel brushed panels bonded to a fiberglass underbody. It's not fully rustproof — it CAN stain, especially from brake dust and salt. Here's my full protocol: Start with a thorough wash using pH-neutral soap, then degrease with isopropyl alcohol, then apply Flitz metal polish with a microfiber in the direction of the grain...",
    author_id: "member-010",
    author_name: "Amanda Wilson",
    created_at: "2025-11-10T10:30:00Z",
    updated_at: "2026-03-15T14:20:00Z",
    reply_count: 143,
    view_count: 8721,
    is_pinned: true,
    is_locked: false,
    tags: ["stainless steel", "detailing", "polishing", "cleaning", "guide"],
  },
  {
    id: "thread-008",
    category_id: "cat-002",
    title: "Alternator upgrade options for high-draw accessories",
    body: "Running a full LED conversion, upgraded sound system, and an EV-style heated seat retrofit has got my stock alternator struggling on cold mornings. The stock unit is rated at 65A — I want to upgrade to at least 100A. Has anyone done this? I've seen some custom brackets being made for Bosch units from modern cars. Looking for recommendations on units that fit without modifications if possible.",
    author_id: "member-022",
    author_name: "Amber Hall",
    created_at: "2026-02-18T11:55:00Z",
    updated_at: "2026-03-12T09:44:00Z",
    reply_count: 15,
    view_count: 512,
    is_pinned: false,
    is_locked: false,
    tags: ["electrical", "alternator", "upgrade", "accessories"],
  },
  // Events
  {
    id: "thread-009",
    category_id: "cat-004",
    title: "DeLorean Expo 2026 — Who's going? Build your caravan here!",
    body: "The big one is coming up — DeLorean Expo 2026 at the Humble, TX facility, August 14-17! Last year we had 340 cars on the field and I expect we'll break 400 this year. If you're planning to drive from the Midwest or Northeast, let's coordinate a caravan. We drove in convoy from Chicago last year — 22 cars and it was an absolute highlight. Comment with your planned route and we'll find convoy buddies.",
    author_id: "member-023",
    author_name: "Brandon Allen",
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-26T21:08:00Z",
    reply_count: 68,
    view_count: 3412,
    is_pinned: true,
    is_locked: false,
    tags: ["Expo 2026", "caravan", "Texas", "annual event"],
  },
  {
    id: "thread-010",
    category_id: "cat-004",
    title: "UK Spring Meet — Oxford, May 10th",
    body: "The UK chapter spring meet is confirmed for Saturday May 10th, at the Blenheim Palace grounds in Oxford. We have permission from the estate for up to 80 cars on the gravel forecourt. Proposed schedule: 10am arrival, 12pm group lunch at the Woodstock Arms, 3pm walking tour of the Palace. Last year we had 52 cars — let's beat that! RSVP in this thread so I can manage headcount.",
    author_id: "member-116",
    author_name: "Nigel Ashworth",
    created_at: "2026-03-05T14:30:00Z",
    updated_at: "2026-03-20T16:15:00Z",
    reply_count: 34,
    view_count: 1128,
    is_pinned: false,
    is_locked: false,
    tags: ["UK", "spring meet", "Oxford", "chapter event"],
  },
  // EV Conversions
  {
    id: "thread-011",
    category_id: "cat-005",
    title: "Tesla motor vs Chevy Bolt motor — 2026 cost/performance comparison",
    body: "The two most popular EV conversion bases are the Tesla Model S rear motor and the Chevy Bolt drive unit. I've done extensive research and spoken with 12 members who've completed conversions. Here's my breakdown: Tesla Motor: Better performance ceiling (150-300hp depending on variant), more development support, but costs 2-3x as much. Bolt Motor: Simpler, cheaper, adequate power (145hp), excellent reliability data, easier packaging in the DeLorean's rear frame...",
    author_id: "member-006",
    author_name: "Jennifer Williams",
    created_at: "2026-02-14T20:15:00Z",
    updated_at: "2026-03-27T06:30:00Z",
    reply_count: 94,
    view_count: 5634,
    is_pinned: true,
    is_locked: false,
    tags: ["EV", "Tesla", "Chevy Bolt", "comparison", "motors"],
  },
  {
    id: "thread-012",
    category_id: "cat-005",
    title: "Battery management systems — which BMS for a DeLorean EV?",
    body: "Building my EV conversion and at the BMS stage. I'm using 280Ah LFP prismatic cells in a 72s1p configuration for 230V nominal. Looking at options: Orion BMS 2, REC BMS, and the DIY-friendly Batrium. Anyone with real-world experience on longevity and cell balancing on these? The Orion is the most popular but it's expensive. The Batrium had a firmware update in January that supposedly fixed the balancing issues...",
    author_id: "member-050",
    author_name: "Zena Cross",
    created_at: "2026-03-12T17:40:00Z",
    updated_at: "2026-03-23T11:22:00Z",
    reply_count: 27,
    view_count: 1089,
    is_pinned: false,
    is_locked: false,
    tags: ["BMS", "battery", "LFP", "EV", "electronics"],
  },
  // Restoration
  {
    id: "thread-013",
    category_id: "cat-006",
    title: "Full frame-off restoration thread — 1981 DMC-12 over 3 years",
    body: "I'm documenting my ongoing restoration here. Car was purchased in 2023 as a running project — mechanically sound but cosmetically rough. Year 1 was teardown and assessment. Year 2 was the fiberglass underbody repair and fresh powder coat of the frame. Year 3 (current) is reassembly with all-new rubber, electrical, and a rebuilt PRV to factory spec. Photo updates posted monthly. Current status: reassembly 60% complete.",
    author_id: "member-070",
    author_name: "Graham Spencer",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2026-03-18T15:30:00Z",
    reply_count: 215,
    view_count: 12847,
    is_pinned: false,
    is_locked: false,
    tags: ["restoration", "frame-off", "build thread", "1981"],
  },
  // Buying
  {
    id: "thread-014",
    category_id: "cat-003",
    title: "Pre-purchase inspection checklist — what to check when buying a DMC-12",
    body: "I've helped 14 DOA members buy their first DeLorean and I've developed a pre-purchase inspection checklist. This is for buyers who are not mechanics but want to know what to look at before bringing a PPI (professional pre-purchase inspection) technician. Critical checks: door strut function (both doors, hold position at full open), VIN verification against build sheet...",
    author_id: "member-009",
    author_name: "Christopher Davis",
    created_at: "2025-09-01T09:30:00Z",
    updated_at: "2026-02-14T14:00:00Z",
    reply_count: 73,
    view_count: 6234,
    is_pinned: true,
    is_locked: false,
    tags: ["buying", "PPI", "checklist", "guide", "first-time"],
  },
  // Regional
  {
    id: "thread-015",
    category_id: "cat-007",
    title: "Pacific Chapter Group Drive — Pacific Coast Highway, June 21",
    body: "Calling all Pacific chapter members! We're planning our annual PCH drive on June 21st. Start point: Santa Monica Pier, 9am. End point: San Luis Obispo, estimated arrival 5pm with stops. Route takes us through Malibu, Oxnard, Santa Barbara, and Pismo Beach. Last year we had 18 cars — hoping for 25+ this year. Lunch stop at the Hitching Post Steakhouse in Buellton (famous from the movie Sideways).",
    author_id: "member-002",
    author_name: "Robert Mitchell",
    created_at: "2026-03-18T11:00:00Z",
    updated_at: "2026-03-26T10:17:00Z",
    reply_count: 22,
    view_count: 841,
    is_pinned: false,
    is_locked: false,
    tags: ["Pacific", "group drive", "PCH", "California"],
  },
  // Off-Topic
  {
    id: "thread-016",
    category_id: "cat-008",
    title: "Back to the Future 4 — is it happening? The latest rumors",
    body: "Universal has been very quiet but the rumor mill is churning again. A reliable Hollywood trades insider reported that Bob Gale was in discussions about a limited series rather than a feature film. The DeLorean is obviously central to any revival. I for one would love to see what they do with it — but I'll be the first to admit nothing should touch the original trilogy. What's the DOA community's take?",
    author_id: "member-040",
    author_name: "Andrew White",
    created_at: "2026-03-22T21:00:00Z",
    updated_at: "2026-03-25T22:33:00Z",
    reply_count: 38,
    view_count: 2104,
    is_pinned: false,
    is_locked: false,
    tags: ["BTTF", "movies", "culture", "off-topic"],
  },
];

export const FORUM_REPLIES: ForumReply[] = [
  // Replies for thread-001 (new owner)
  {
    id: "reply-001",
    thread_id: "thread-001",
    author_id: "member-009",
    author_name: "Christopher Davis",
    body: "Welcome to the family! First priority: don't drive it until you've checked the timing chain. If it's original and at 38k miles with an unknown service history, you want to do that before anything else. The PRV V6 timing chain is the Achilles heel of these cars — if it goes, you're looking at major engine damage. Check my pinned guide in Tech Talk.",
    created_at: "2026-03-20T16:00:00Z",
    is_solution: false,
  },
  {
    id: "reply-002",
    thread_id: "thread-001",
    author_id: "member-010",
    author_name: "Amanda Wilson",
    body: "Congratulations! Estate sale finds are often the best — the cars haven't been flipped by dealers. The 1982 is a great vintage. After timing chain, I'd check: 1) door struts, 2) coolant hoses (they get brittle), 3) fuel system condition. Photos?",
    created_at: "2026-03-20T16:45:00Z",
    is_solution: false,
  },
  {
    id: "reply-003",
    thread_id: "thread-001",
    author_id: "member-001",
    author_name: "James Schay",
    body: "Welcome! I just joined DOA a couple years ago myself and the community here is incredible. Everyone is willing to help. Take your time, document everything you find, and don't rush the first repairs. These cars respond well to patience.",
    created_at: "2026-03-20T18:22:00Z",
    is_solution: false,
  },
  // Replies for thread-004 (timing chain guide)
  {
    id: "reply-004",
    thread_id: "thread-004",
    author_id: "member-012",
    author_name: "Laura Garcia",
    body: "This is the best resource on the internet for this job. I followed this guide last summer — took me 16 hours spread over a weekend. Car runs perfectly now. One thing I'd add: replace the water pump at the same time since you're already in there.",
    created_at: "2026-01-16T10:00:00Z",
    is_solution: false,
  },
  {
    id: "reply-005",
    thread_id: "thread-004",
    author_id: "member-030",
    author_name: "Iris Nelson",
    body: "Saved me $2,000 in shop labor. Thank you! I rented the cam sprocket tool from the local O'Reilly's — didn't realize that was an option until I asked.",
    created_at: "2026-01-18T15:30:00Z",
    is_solution: true,
  },
  // Replies for thread-005 (door struts)
  {
    id: "reply-006",
    thread_id: "thread-005",
    author_id: "member-010",
    author_name: "Amanda Wilson",
    body: "I've tried all three vendors. For quality: DMC Texas is consistently excellent (their struts are made in Germany to spec). DMCH is good too. Stay away from the eBay Chinese knockoffs — I had two fail within 6 months. The hydraulic conversion is interesting but overkill unless you're building a show car.",
    created_at: "2026-03-10T15:00:00Z",
    is_solution: false,
  },
  {
    id: "reply-007",
    thread_id: "thread-005",
    author_id: "member-009",
    author_name: "Christopher Davis",
    body: "Agree with Amanda on DMC Texas struts. The hydraulic conversion from SunStar is beautiful and was about $850 when I did mine in 2022. Worth it if you're keeping the car long-term. The doors now hold at any position and the operation is silky smooth.",
    created_at: "2026-03-11T09:15:00Z",
    is_solution: false,
  },
  // Replies for thread-011 (EV motors)
  {
    id: "reply-008",
    thread_id: "thread-011",
    author_id: "member-006",
    author_name: "Jennifer Williams",
    body: "Update from 6 months of daily driving my Tesla motor build: 250 miles of range, charges to 80% in 35 minutes on a DC fast charger. Zero issues. Would do it again.",
    created_at: "2026-02-20T20:30:00Z",
    is_solution: false,
  },
  {
    id: "reply-009",
    thread_id: "thread-011",
    author_id: "member-050",
    author_name: "Zena Cross",
    body: "Currently building my Bolt motor conversion. Total parts cost so far: $8,400. The Tesla equivalent would have been $22,000+. For me the math was easy. It will make about 145hp — plenty for a 2,700 lb car.",
    created_at: "2026-02-22T14:45:00Z",
    is_solution: false,
  },
  // Replies for thread-009 (Expo)
  {
    id: "reply-010",
    thread_id: "thread-009",
    author_id: "member-001",
    author_name: "James Schay",
    body: "Planning to drive down from Portland! That's about 2,200 miles round trip. I'll join any Pacific Coast caravan that's heading south. Who else is coming from the Pacific Northwest?",
    created_at: "2026-03-02T10:00:00Z",
    is_solution: false,
  },
  {
    id: "reply-011",
    thread_id: "thread-009",
    author_id: "member-003",
    author_name: "Sarah Chen",
    body: "Coming from SF! Will join the PCH caravan from Santa Barbara south, then cut over to Texas. Happy to coordinate with anyone going that direction.",
    created_at: "2026-03-02T12:30:00Z",
    is_solution: false,
  },
];

export const getThreadsByCategory = (categoryId: string) =>
  FORUM_THREADS.filter((t) => t.category_id === categoryId);

export const getThreadById = (id: string) =>
  FORUM_THREADS.find((t) => t.id === id);

export const getRepliesByThread = (threadId: string) =>
  FORUM_REPLIES.filter((r) => r.thread_id === threadId);

export const getCategoryById = (id: string) =>
  FORUM_CATEGORIES.find((c) => c.id === id);
