import { MagazineIssue } from "@/lib/types";

export const MOCK_MAGAZINE_ISSUES: MagazineIssue[] = [
  {
    id: "mag-001",
    volume: 32,
    issue: 1,
    title: "EV Revolution — The Electric Future of Our Beloved DMC-12",
    cover_story: "With over 40 members now driving electric DeLoreans, we explore what an EV conversion means for the community — and whether it honors or betrays the DMC-12's legacy.",
    published_date: "2026-02-01",
    cover_placeholder: "mag-ev-gradient",
    page_count: 52,
    highlights: [
      "Tesla vs Bolt motor — full comparison",
      "Member spotlight: Jennifer Williams's 250-mile Tesla build",
      "Tech: BMS options for DIY converters",
      "The debate: EV conversion — yes or no?",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-002",
    volume: 31,
    issue: 4,
    title: "Ladies of Stainless — Women Shaping the DeLorean Community",
    cover_story: "Meet the 47 women members who are owners, restorers, and advocates in the DeLorean community. Their stories, their cars, and their contributions to the DOA.",
    published_date: "2025-11-01",
    cover_placeholder: "mag-ladies-gradient",
    page_count: 48,
    highlights: [
      "12 member profiles",
      "Sarah Chen's Pacific chapter leadership",
      "The making of a restoration engineer",
      "BTTF 40th anniversary reflections",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-003",
    volume: 31,
    issue: 3,
    title: "40th Anniversary Special — DOA Since 1983",
    cover_story: "The DeLorean Owners Association marks 40 years. From a handful of enthusiasts to a 5,000-member global community — how we got here and where we're going.",
    published_date: "2025-08-01",
    cover_placeholder: "mag-40th-gradient",
    page_count: 84,
    highlights: [
      "40-year history of the DOA",
      "Founding member interviews",
      "The cars that defined each decade",
      "Chapter histories from around the world",
      "Special: the John DeLorean legacy",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-004",
    volume: 31,
    issue: 2,
    title: "The Restoration Bible — Complete Guide for 2025",
    cover_story: "Everything you need to know about restoring a DMC-12 in 2025: parts availability, vendor reviews, what to restore vs. preserve, and how to find a good specialist.",
    published_date: "2025-05-01",
    cover_placeholder: "mag-restoration-gradient",
    page_count: 60,
    highlights: [
      "Parts vendor comparison 2025",
      "Stainless steel panel restoration guide",
      "PRV V6 complete rebuild walkthrough",
      "Interior restoration: leather and carpet sources",
      "Reader restorations: 5 inspiring builds",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-005",
    volume: 31,
    issue: 1,
    title: "Garage Finds — Unearthing Lost DeLoreans",
    cover_story: "Barn finds, garage finds, estate sales: members share stories of discovering unknown DeLoreans in unlikely places, and what happened next.",
    published_date: "2025-02-01",
    cover_placeholder: "mag-barnfind-gradient",
    page_count: 44,
    highlights: [
      "7 incredible garage find stories",
      "How to assess a neglected DMC-12",
      "The lowest-mileage DeLorean known: 5,300 miles",
      "Preservation vs restoration debate",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-006",
    volume: 30,
    issue: 4,
    title: "Expo 2025 Recap — 340 Cars, Record Attendance",
    cover_story: "The DeLorean Expo 2025 was the biggest yet — 340 cars, 800 attendees, and memories for a lifetime. Full photo coverage inside.",
    published_date: "2024-11-01",
    cover_placeholder: "mag-expo-gradient",
    page_count: 56,
    highlights: [
      "Full photo coverage — 40 pages",
      "Best in show results",
      "Tech seminar summaries",
      "2026 Expo announced",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-007",
    volume: 30,
    issue: 3,
    title: "Performance Builds — When Stock Just Won't Do",
    cover_story: "From turbo PRV builds to LS swaps, the performance community within DOA is growing. We profile the five most extreme performance DeLoreans in the membership.",
    published_date: "2024-08-01",
    cover_placeholder: "mag-performance-gradient",
    page_count: 48,
    highlights: [
      "LS3 swap: 420hp street build",
      "Twin-turbo PRV: 225whp tested",
      "Track day guide for DeLorean owners",
      "Suspension upgrades compared",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-008",
    volume: 30,
    issue: 2,
    title: "The Gold Standard — Rare and Unusual DeLorean Variants",
    cover_story: "Beyond stainless: the rare gold, black, and blue factory DeLoreans, plus some of the most unusual modifications ever done to a DMC-12.",
    published_date: "2024-05-01",
    cover_placeholder: "mag-gold-gradient",
    page_count: 44,
    highlights: [
      "All known gold DeLoreans profiled",
      "Factory blue: more common than you think?",
      "The most unusual modifications",
      "Replica cars: BTTF and Ecto-1 builds",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-009",
    volume: 30,
    issue: 1,
    title: "Daily Driver — Living With Your DeLorean Year-Round",
    cover_story: "Five members who drive their DeLoreans every day — not just to shows. Their experiences, tips, and the reality of 365-day DeLorean ownership.",
    published_date: "2024-02-01",
    cover_placeholder: "mag-daily-gradient",
    page_count: 40,
    highlights: [
      "5 daily driver profiles",
      "Winter storage vs winter driving",
      "Reliability improvement guide",
      "Parts you should always carry",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-010",
    volume: 29,
    issue: 4,
    title: "International Chapter Report — A Truly Global Community",
    cover_story: "From Belfast to Brisbane, from Tokyo to Buenos Aires — the DeLorean community is global. A tour of international DOA chapters and their members.",
    published_date: "2023-11-01",
    cover_placeholder: "mag-international-gradient",
    page_count: 52,
    highlights: [
      "UK chapter: largest outside USA",
      "Europe chapter highlights",
      "Australia's unique DeLorean scene",
      "Japan: the ultra-rare right-hand drive cars",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-011",
    volume: 29,
    issue: 3,
    title: "The Stainless Steel Deep Dive — Everything About DMC Bodywork",
    cover_story: "The definitive technical guide to DeLorean bodywork — what it's made of, how to care for it, what can go wrong, and what original factory spec looks like.",
    published_date: "2023-08-01",
    cover_placeholder: "mag-stainless-gradient",
    page_count: 48,
    highlights: [
      "Stainless steel metallurgy explained",
      "Panel polishing: full photographic guide",
      "Rust and staining: causes and cures",
      "When panels need replacement",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-012",
    volume: 29,
    issue: 2,
    title: "Back to the Future at 40 — The Film That Immortalized Us",
    cover_story: "Back to the Future turns 40. A celebration of the film that made the DeLorean the most iconic car in cinema history, featuring interviews with BTTF historians and DOA members who were watching in 1985.",
    published_date: "2023-05-01",
    cover_placeholder: "mag-bttf-gradient",
    page_count: 68,
    highlights: [
      "The making of the time machine",
      "Every DeLorean prop car: where are they now?",
      "Members who saw BTTF in theaters",
      "BTTF's effect on DeLorean values",
      "The fans: 40 years of love",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-013",
    volume: 29,
    issue: 1,
    title: "Buying Guide 2023 — Everything You Need to Know",
    cover_story: "The market for DMC-12s has shifted significantly. Here's our annual buying guide: what cars cost, what to look for, how to find one, and how to avoid the lemons.",
    published_date: "2023-02-01",
    cover_placeholder: "mag-buying-gradient",
    page_count: 44,
    highlights: [
      "2023 market overview",
      "PPI guide: 50-point checklist",
      "Avoiding the bad actors",
      "True cost of ownership analysis",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-014",
    volume: 28,
    issue: 4,
    title: "The PRV V6 — A Technical Love Letter",
    cover_story: "The engine everyone loves to complain about is actually a remarkable piece of engineering. A deep technical appreciation of the PRV V6 — its history, its quirks, and why it keeps going.",
    published_date: "2022-11-01",
    cover_placeholder: "mag-prv-gradient",
    page_count: 52,
    highlights: [
      "PRV V6 history: Peugeot, Renault, Volvo",
      "Why the DMC engine specs were different",
      "The common failure points",
      "Complete engine rebuild guide",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-015",
    volume: 28,
    issue: 3,
    title: "DeLorean Expo 2022 — Celebrating 40 Years of the DMC-12",
    cover_story: "The 40th anniversary of the DMC-12 was celebrated in style. 280 cars gathered in Texas for the biggest DeLorean event in years.",
    published_date: "2022-08-01",
    cover_placeholder: "mag-expo22-gradient",
    page_count: 60,
    highlights: [
      "Full expo coverage",
      "40th anniversary commemorative cars",
      "John DeLorean: a complicated legacy",
      "What the next 40 years holds",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-016",
    volume: 27,
    issue: 2,
    title: "Digital Restoration — Using Modern Technology on a Classic",
    cover_story: "How modern technology tools — 3D printing, laser scanning, digital diagnostics — are changing how we restore and maintain DeLoreans.",
    published_date: "2021-05-01",
    cover_placeholder: "mag-digital-gradient",
    page_count: 44,
    highlights: [
      "3D printing rare parts",
      "OBD2 adapters for the PRV",
      "Digital photography in documentation",
      "Member tech projects",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-017",
    volume: 26,
    issue: 4,
    title: "COVID Chronicles — How We Kept the Community Together",
    cover_story: "The pandemic year in review: how the DOA pivoted to virtual events, kept the magazine going, and members kept their cars running through the lockdowns.",
    published_date: "2020-11-01",
    cover_placeholder: "mag-covid-gradient",
    page_count: 40,
    highlights: [
      "Virtual meet coverage",
      "Garage projects from lockdown",
      "Member connections maintained",
      "The first virtual Expo",
    ],
    is_digital_only: true,
  },
  {
    id: "mag-018",
    volume: 26,
    issue: 1,
    title: "The DeLorean Factory — A Photographic Journey",
    cover_story: "Rare photographs from inside the Dunmurry factory, circa 1981-82. These images, published here for the first time, show the production line in detail.",
    published_date: "2020-02-01",
    cover_placeholder: "mag-factory-gradient",
    page_count: 48,
    highlights: [
      "40+ unpublished factory photos",
      "Worker recollections from Dunmurry",
      "The production process explained",
      "How many were really made?",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-019",
    volume: 25,
    issue: 3,
    title: "Concours or Driver? The Great DeLorean Debate",
    cover_story: "The eternal question: should your DeLorean be a museum piece or a road car? Members argue both sides with passion.",
    published_date: "2019-08-01",
    cover_placeholder: "mag-debate-gradient",
    page_count: 44,
    highlights: [
      "Concours champion builds profiled",
      "Daily drivers defend their choices",
      "The financial case for each approach",
      "Values over 20 years",
    ],
    is_digital_only: false,
  },
  {
    id: "mag-020",
    volume: 25,
    issue: 1,
    title: "DOA at 35 — Where Have We Come From, Where Are We Going?",
    cover_story: "A milestone look at 35 years of the DeLorean Owners Association — from newsletter origins to a global digital community.",
    published_date: "2019-02-01",
    cover_placeholder: "mag-35th-gradient",
    page_count: 52,
    highlights: [
      "35-year retrospective",
      "First members: where are they now?",
      "The magazine archive",
      "Future plans for the DOA",
    ],
    is_digital_only: false,
  },
];

export const getLatestIssues = (count: number = 4) =>
  [...MOCK_MAGAZINE_ISSUES]
    .sort((a, b) => new Date(b.published_date).getTime() - new Date(a.published_date).getTime())
    .slice(0, count);

export const getMagazineById = (id: string) =>
  MOCK_MAGAZINE_ISSUES.find((m) => m.id === id);
