import { ServiceCenter } from "@/lib/types";

export const MOCK_SERVICE_CENTERS: ServiceCenter[] = [
  {
    id: "sc-001",
    name: "DeLorean Motor Company",
    address: "24625 State Hwy 198",
    city: "Humble",
    state: "TX",
    country: "USA",
    lat: 29.9988,
    lng: -95.2581,
    phone: "+1 (832) 201-4002",
    email: "parts@delorean.com",
    website: "https://www.delorean.com",
    specialties: ["Parts Sales", "Mechanical", "Electrical", "Restoration", "Body Work"],
    description: "The official DeLorean Motor Company — the world's primary source for DeLorean parts and service. The genuine article. If there's a part for your DMC-12, they have it or can get it.",
    is_official_dmc: true,
  },
  {
    id: "sc-002",
    name: "PJ Grady Inc.",
    address: "47 Dwight Place",
    city: "Fairfield",
    state: "NJ",
    country: "USA",
    lat: 40.8857,
    lng: -74.3031,
    phone: "+1 (973) 575-3322",
    email: "service@pjgrady.com",
    website: "https://www.pjgrady.com",
    specialties: ["Mechanical", "Electrical", "Restoration", "Parts"],
    description: "PJ Grady is the East Coast's premier DeLorean specialist. Operating since 1984, they have decades of institutional knowledge and are the go-to shop for the Northeast chapter.",
    is_official_dmc: false,
  },
  {
    id: "sc-003",
    name: "DeLorean Midwest",
    address: "4521 N. Lincoln Ave",
    city: "Chicago",
    state: "IL",
    country: "USA",
    lat: 41.9632,
    lng: -87.6857,
    phone: "+1 (773) 555-0134",
    email: "service@deloreanmidwest.com",
    specialties: ["Mechanical", "Electrical", "Performance Upgrades", "EV Conversion"],
    description: "Midwest chapter's preferred shop. Specializes in both traditional service and modern upgrades including turbo kits and EV conversions. Run by chapter member and master technician Christopher Davis.",
    is_official_dmc: false,
  },
  {
    id: "sc-004",
    name: "DeLorean One",
    address: "5450 N. 51st Ave, Suite B",
    city: "Glendale",
    state: "AZ",
    country: "USA",
    lat: 33.5386,
    lng: -112.1458,
    phone: "+1 (623) 555-0287",
    email: "info@deloreanone.com",
    website: "https://www.deloreanone.com",
    specialties: ["Mechanical", "Parts", "EV Conversion", "Performance"],
    description: "Southwest specialist offering complete mechanical service, parts supply, and EV conversions. One of the only shops in the Southwest certified to do EV conversions.",
    is_official_dmc: false,
  },
  {
    id: "sc-005",
    name: "DeLorean West",
    address: "7821 Miramar Road",
    city: "San Diego",
    state: "CA",
    country: "USA",
    lat: 32.8896,
    lng: -117.1651,
    phone: "+1 (858) 555-0412",
    email: "service@deloreanwest.com",
    specialties: ["Mechanical", "Electrical", "Restoration", "Body Work", "Stainless Polish"],
    description: "Southern California's finest DeLorean shop. Particularly noted for their stainless steel body work and their ability to source California-clean project cars.",
    is_official_dmc: false,
  },
  {
    id: "sc-006",
    name: "DeLorean of Florida",
    address: "12450 NW 39th Street",
    city: "Coral Springs",
    state: "FL",
    country: "USA",
    lat: 26.2712,
    lng: -80.2708,
    phone: "+1 (954) 555-0223",
    email: "service@deloreanflorida.com",
    specialties: ["Mechanical", "Electrical", "A/C Service", "Restoration"],
    description: "Southeast specialist with particular expertise in A/C systems (essential in Florida) and preventing or treating salt air corrosion. Serves the Southeast chapter.",
    is_official_dmc: false,
  },
  {
    id: "sc-007",
    name: "Pacific DeLorean Service",
    address: "2305 Airport Way S",
    city: "Seattle",
    state: "WA",
    country: "USA",
    lat: 47.5724,
    lng: -122.3218,
    phone: "+1 (206) 555-0178",
    email: "info@pacificdelorean.com",
    specialties: ["Mechanical", "Electrical", "EV Conversion"],
    description: "Pacific Northwest's specialist for DeLorean service and one of the pioneering shops for EV conversions. Known in the community for their innovative approaches.",
    is_official_dmc: false,
  },
  {
    id: "sc-008",
    name: "PJ Grady UK",
    address: "Unit 14, Watford Business Centre",
    city: "Watford",
    state: "Hertfordshire",
    country: "UK",
    lat: 51.6557,
    lng: -0.3963,
    phone: "+44 1923 555 0134",
    email: "service@pjgrady.co.uk",
    website: "https://www.pjgrady.co.uk",
    specialties: ["Mechanical", "Electrical", "Restoration", "MOT Preparation", "Parts"],
    description: "The UK's leading DeLorean specialist, affiliated with PJ Grady in the USA. The only UK shop with direct access to all DMC Texas parts stock. Prepares cars for MOT.",
    is_official_dmc: false,
  },
  {
    id: "sc-009",
    name: "European DeLorean Centre",
    address: "Römerstrasse 88",
    city: "Cologne",
    state: "North Rhine-Westphalia",
    country: "Germany",
    lat: 50.9380,
    lng: 6.9602,
    phone: "+49 221 5550 0234",
    email: "service@eurodelcentre.de",
    specialties: ["Mechanical", "Electrical", "TÜV Preparation", "Parts Import"],
    description: "Germany's premier DeLorean shop, serving all of continental Europe. Specializes in getting European-spec cars through TÜV (German technical inspection). Ships parts throughout Europe.",
    is_official_dmc: false,
  },
  {
    id: "sc-010",
    name: "DeLorean Specialists of Texas",
    address: "8100 Shoal Creek Blvd",
    city: "Austin",
    state: "TX",
    country: "USA",
    lat: 30.3604,
    lng: -97.7389,
    phone: "+1 (512) 555-0367",
    email: "service@dstexas.com",
    specialties: ["Mechanical", "Performance", "Engine Rebuilds", "Turbo Kits"],
    description: "Austin shop known for their performance work — turbo kits, engine rebuilds, and suspension tuning. Popular with the local track day crowd.",
    is_official_dmc: false,
  },
  {
    id: "sc-011",
    name: "DeLorean Northeast Restoration",
    address: "44 Industrial Blvd",
    city: "Albany",
    state: "NY",
    country: "USA",
    lat: 42.6526,
    lng: -73.7562,
    phone: "+1 (518) 555-0192",
    email: "restore@dloreanNE.com",
    specialties: ["Full Restoration", "Body Work", "Interior Restoration", "Rust Treatment"],
    description: "Upstate NY shop specializing in full and partial restorations. Particularly skilled at dealing with rust and salt damage from Northeast winters. Chapter-endorsed for restoration work.",
    is_official_dmc: false,
  },
  {
    id: "sc-012",
    name: "Stainless Steel Dreams",
    address: "3200 N. Nash Street",
    city: "El Segundo",
    state: "CA",
    country: "USA",
    lat: 33.9175,
    lng: -118.4017,
    phone: "+1 (310) 555-0241",
    email: "info@stainlesssteeledreams.com",
    specialties: ["Show Prep", "Detailing", "Stainless Polish", "Concours Restoration"],
    description: "The go-to shop for show car preparation. They've prepped multiple DeLoreans for Pebble Beach and are the acknowledged masters of stainless steel detailing.",
    is_official_dmc: false,
  },
  {
    id: "sc-013",
    name: "Southern EV Conversions",
    address: "555 Technology Blvd",
    city: "Nashville",
    state: "TN",
    country: "USA",
    lat: 36.1735,
    lng: -86.8043,
    phone: "+1 (615) 555-0398",
    email: "ev@southernevconversions.com",
    specialties: ["EV Conversion", "Battery Systems", "Charging Infrastructure"],
    description: "Dedicated EV conversion shop that serves the Southeast and Southwest. Has completed 8 DeLorean conversions. Package prices available for both budget and premium builds.",
    is_official_dmc: false,
  },
  {
    id: "sc-014",
    name: "DeLorean Australia",
    address: "23 Botany Road",
    city: "Alexandria",
    state: "NSW",
    country: "Australia",
    lat: -33.9088,
    lng: 151.1955,
    phone: "+61 2 9555 0123",
    email: "service@deloreanaustralia.com.au",
    website: "https://www.deloreanaustralia.com.au",
    specialties: ["Mechanical", "RHD Conversion", "Parts Import", "Compliance"],
    description: "Australia's only dedicated DeLorean specialist. Handles compliance and registration for imported cars, RHD conversions, and all service. Serves the Australian chapter.",
    is_official_dmc: false,
  },
  {
    id: "sc-015",
    name: "DeLorean Performance Works",
    address: "4400 SW 41st Street",
    city: "Miami",
    state: "FL",
    country: "USA",
    lat: 25.7782,
    lng: -80.2869,
    phone: "+1 (305) 555-0155",
    email: "info@deloreanperformance.com",
    specialties: ["Performance", "LS Swap", "Suspension", "Brakes"],
    description: "Miami shop focused on performance builds — LS swaps, suspension upgrades, and big brake kits. If you want your DeLorean to be the fastest thing on the road, call these guys.",
    is_official_dmc: false,
  },
];

export const getServiceCenterById = (id: string) =>
  MOCK_SERVICE_CENTERS.find((s) => s.id === id);

export const getServiceCentersByCountry = (country: string) =>
  MOCK_SERVICE_CENTERS.filter((s) => s.country === country);

export const getNearestServiceCenters = (lat: number, lng: number, count: number = 5) => {
  const dist = (a: ServiceCenter) => {
    const dLat = a.lat - lat;
    const dLng = a.lng - lng;
    return Math.sqrt(dLat * dLat + dLng * dLng);
  };
  return [...MOCK_SERVICE_CENTERS].sort((a, b) => dist(a) - dist(b)).slice(0, count);
};
